
# This file is automatically generated, you probably don't want to edit this

createdesignOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "createdesignOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            showdescription = FALSE,
            expdesign = "2k",
            nvars = 3,
            nlevels = 3,
            resolut = "5",
            cubecp = 3,
            starcp = 1,
            inscribed = FALSE,
            staralpha = "rotatable", ...) {

            super$initialize(
                package="FoodieStats",
                name="createdesign",
                requiresData=TRUE,
                ...)

            private$..showdescription <- jmvcore::OptionBool$new(
                "showdescription",
                showdescription,
                default=FALSE)
            private$..expdesign <- jmvcore::OptionList$new(
                "expdesign",
                expdesign,
                options=list(
                    "2k",
                    "3k",
                    "ff2k",
                    "bbd",
                    "ccd",
                    "scd",
                    "sld"),
                default="2k")
            private$..nvars <- jmvcore::OptionNumber$new(
                "nvars",
                nvars,
                default=3,
                min=2,
                max=25)
            private$..nlevels <- jmvcore::OptionNumber$new(
                "nlevels",
                nlevels,
                default=3,
                min=2,
                max=99)
            private$..resolut <- jmvcore::OptionList$new(
                "resolut",
                resolut,
                options=list(
                    "3",
                    "4",
                    "5"),
                default="5")
            private$..cubecp <- jmvcore::OptionNumber$new(
                "cubecp",
                cubecp,
                default=3,
                min=0,
                max=99)
            private$..starcp <- jmvcore::OptionNumber$new(
                "starcp",
                starcp,
                default=1,
                min=0,
                max=99)
            private$..inscribed <- jmvcore::OptionBool$new(
                "inscribed",
                inscribed,
                default=FALSE)
            private$..staralpha <- jmvcore::OptionList$new(
                "staralpha",
                staralpha,
                options=list(
                    "rotatable",
                    "orthogonal",
                    "spherical",
                    "faces"),
                default="rotatable")

            self$.addOption(private$..showdescription)
            self$.addOption(private$..expdesign)
            self$.addOption(private$..nvars)
            self$.addOption(private$..nlevels)
            self$.addOption(private$..resolut)
            self$.addOption(private$..cubecp)
            self$.addOption(private$..starcp)
            self$.addOption(private$..inscribed)
            self$.addOption(private$..staralpha)
        }),
    active = list(
        showdescription = function() private$..showdescription$value,
        expdesign = function() private$..expdesign$value,
        nvars = function() private$..nvars$value,
        nlevels = function() private$..nlevels$value,
        resolut = function() private$..resolut$value,
        cubecp = function() private$..cubecp$value,
        starcp = function() private$..starcp$value,
        inscribed = function() private$..inscribed$value,
        staralpha = function() private$..staralpha$value),
    private = list(
        ..showdescription = NA,
        ..expdesign = NA,
        ..nvars = NA,
        ..nlevels = NA,
        ..resolut = NA,
        ..cubecp = NA,
        ..starcp = NA,
        ..inscribed = NA,
        ..staralpha = NA)
)

createdesignResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "createdesignResults",
    inherit = jmvcore::Group,
    active = list(
        description = function() private$.items[["description"]],
        designtabletitle = function() private$.items[["designtabletitle"]],
        designtable = function() private$.items[["designtable"]],
        designplot = function() private$.items[["designplot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Create an Experimental Design")
            self$add(jmvcore::Html$new(
                options=options,
                name="description",
                title="description",
                visible="(showdescription)"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="designtabletitle",
                title="Experimental Design Table"))
            self$add(jmvcore::Table$new(
                options=options,
                name="designtable",
                title="Experimental Design Table with coded factors",
                columns=list()))
            self$add(jmvcore::Image$new(
                options=options,
                name="designplot",
                title="Design Points Plot",
                width=480,
                height=480,
                renderFun=".designplot",
                requiresData=TRUE,
                visible="(expdesign:scd || expdesign:sld)"))}))

createdesignBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "createdesignBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "FoodieStats",
                name = "createdesign",
                version = c(1,0,0),
                options = options,
                results = createdesignResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Create an Experimental Design
#'
#' 
#' @param data .
#' @param showdescription .
#' @param expdesign .
#' @param nvars .
#' @param nlevels .
#' @param resolut .
#' @param cubecp .
#' @param starcp .
#' @param inscribed .
#' @param staralpha .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$description} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$designtabletitle} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$designtable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$designplot} \tab \tab \tab \tab \tab the design points plot \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$designtable$asDF}
#'
#' \code{as.data.frame(results$designtable)}
#'
#' @export
createdesign <- function(
    data,
    showdescription = FALSE,
    expdesign = "2k",
    nvars = 3,
    nlevels = 3,
    resolut = "5",
    cubecp = 3,
    starcp = 1,
    inscribed = FALSE,
    staralpha = "rotatable") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("createdesign requires jmvcore to be installed (restart may be required)")

    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame())


    options <- createdesignOptions$new(
        showdescription = showdescription,
        expdesign = expdesign,
        nvars = nvars,
        nlevels = nlevels,
        resolut = resolut,
        cubecp = cubecp,
        starcp = starcp,
        inscribed = inscribed,
        staralpha = staralpha)

    analysis <- createdesignClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

