
# This file is automatically generated, you probably don't want to edit this

designkmodelOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "designkmodelOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            showdescription = FALSE,
            yield = NULL,
            vars = NULL,
            cats = NULL,
            alphaval = 5,
            showeffects = FALSE,
            showinteraction = FALSE,
            showpareto = FALSE,
            showhalf = FALSE,
            criteria = "Lenth",
            mupdate = "default",
            showrsm = FALSE,
            thetaval = -25,
            phival = 20,
            colorselection = "SpectralStylish", ...) {

            super$initialize(
                package="FoodieStats",
                name="designkmodel",
                requiresData=TRUE,
                ...)

            private$..showdescription <- jmvcore::OptionBool$new(
                "showdescription",
                showdescription,
                default=FALSE)
            private$..yield <- jmvcore::OptionVariable$new(
                "yield",
                yield,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..cats <- jmvcore::OptionVariable$new(
                "cats",
                cats,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..alphaval <- jmvcore::OptionNumber$new(
                "alphaval",
                alphaval,
                default=5,
                min=1,
                max=25)
            private$..showeffects <- jmvcore::OptionBool$new(
                "showeffects",
                showeffects,
                default=FALSE)
            private$..showinteraction <- jmvcore::OptionBool$new(
                "showinteraction",
                showinteraction,
                default=FALSE)
            private$..showpareto <- jmvcore::OptionBool$new(
                "showpareto",
                showpareto,
                default=FALSE)
            private$..showhalf <- jmvcore::OptionBool$new(
                "showhalf",
                showhalf,
                default=FALSE)
            private$..criteria <- jmvcore::OptionList$new(
                "criteria",
                criteria,
                options=list(
                    "Lenth",
                    "Daniel",
                    "JuanPena",
                    "Zahn",
                    "WZahn",
                    "RMS",
                    "SMedian"),
                default="Lenth")
            private$..mupdate <- jmvcore::OptionList$new(
                "mupdate",
                mupdate,
                options=list(
                    "default",
                    "backwardalpha"),
                default="default")
            private$..showrsm <- jmvcore::OptionBool$new(
                "showrsm",
                showrsm,
                default=FALSE)
            private$..thetaval <- jmvcore::OptionNumber$new(
                "thetaval",
                thetaval,
                default=-25,
                min=-180,
                max=180)
            private$..phival <- jmvcore::OptionNumber$new(
                "phival",
                phival,
                default=20,
                min=-180,
                max=180)
            private$..colorselection <- jmvcore::OptionList$new(
                "colorselection",
                colorselection,
                options=list(
                    "SpectralStylish",
                    "JamoviStylish",
                    "BeachStylish",
                    "OceanStylish",
                    "Market",
                    "Gingerbread",
                    "Umami",
                    "SummerSalad",
                    "FruitCup",
                    "Delight",
                    "Greensmoothie",
                    "Turmeric",
                    "Snacks",
                    "Sashimi",
                    "Macarons",
                    "Feast",
                    "Veggies",
                    "Beetroot",
                    "Spice",
                    "Sweet",
                    "Tropical",
                    "Breakfast",
                    "Carrots",
                    "Stick",
                    "Tea",
                    "Decadent",
                    "Berry",
                    "Sugary",
                    "Citrus",
                    "Chard",
                    "Shrimp",
                    "SweetSalad",
                    "Cheesecake",
                    "FruitBasket",
                    "Cayenne",
                    "Smoothie",
                    "Mojito",
                    "Coffee",
                    "Wine",
                    "Beer",
                    "Fish",
                    "Cheese",
                    "Bread",
                    "Chocolate",
                    "Beef",
                    "Honey",
                    "Dairy",
                    "Vegetables",
                    "Bean",
                    "Seafood",
                    "Octopus"),
                default="SpectralStylish")

            self$.addOption(private$..showdescription)
            self$.addOption(private$..yield)
            self$.addOption(private$..vars)
            self$.addOption(private$..cats)
            self$.addOption(private$..alphaval)
            self$.addOption(private$..showeffects)
            self$.addOption(private$..showinteraction)
            self$.addOption(private$..showpareto)
            self$.addOption(private$..showhalf)
            self$.addOption(private$..criteria)
            self$.addOption(private$..mupdate)
            self$.addOption(private$..showrsm)
            self$.addOption(private$..thetaval)
            self$.addOption(private$..phival)
            self$.addOption(private$..colorselection)
        }),
    active = list(
        showdescription = function() private$..showdescription$value,
        yield = function() private$..yield$value,
        vars = function() private$..vars$value,
        cats = function() private$..cats$value,
        alphaval = function() private$..alphaval$value,
        showeffects = function() private$..showeffects$value,
        showinteraction = function() private$..showinteraction$value,
        showpareto = function() private$..showpareto$value,
        showhalf = function() private$..showhalf$value,
        criteria = function() private$..criteria$value,
        mupdate = function() private$..mupdate$value,
        showrsm = function() private$..showrsm$value,
        thetaval = function() private$..thetaval$value,
        phival = function() private$..phival$value,
        colorselection = function() private$..colorselection$value),
    private = list(
        ..showdescription = NA,
        ..yield = NA,
        ..vars = NA,
        ..cats = NA,
        ..alphaval = NA,
        ..showeffects = NA,
        ..showinteraction = NA,
        ..showpareto = NA,
        ..showhalf = NA,
        ..criteria = NA,
        ..mupdate = NA,
        ..showrsm = NA,
        ..thetaval = NA,
        ..phival = NA,
        ..colorselection = NA)
)

designkmodelResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "designkmodelResults",
    inherit = jmvcore::Group,
    active = list(
        description = function() private$.items[["description"]],
        doetable = function() private$.items[["doetable"]],
        doetable2 = function() private$.items[["doetable2"]],
        doeanova = function() private$.items[["doeanova"]],
        anovatable = function() private$.items[["anovatable"]],
        estitabletitleX = function() private$.items[["estitabletitleX"]],
        estitableX = function() private$.items[["estitableX"]],
        maintable = function() private$.items[["maintable"]],
        maintable3kCoded = function() private$.items[["maintable3kCoded"]],
        scalingtitle = function() private$.items[["scalingtitle"]],
        scalingtable = function() private$.items[["scalingtable"]],
        estitabletitle = function() private$.items[["estitabletitle"]],
        estitableOR = function() private$.items[["estitableOR"]],
        maintable2 = function() private$.items[["maintable2"]],
        maintable3k = function() private$.items[["maintable3k"]],
        doedataset = function() private$.items[["doedataset"]],
        cols = function() private$.items[["cols"]],
        rsmformula = function() private$.items[["rsmformula"]],
        showplot = function() private$.items[["showplot"]],
        modellm = function() private$.items[["modellm"]],
        modelrsm = function() private$.items[["modelrsm"]],
        colsrsm = function() private$.items[["colsrsm"]],
        mainplot = function() private$.items[["mainplot"]],
        interactionplot = function() private$.items[["interactionplot"]],
        paretoplot = function() private$.items[["paretoplot"]],
        halfplot = function() private$.items[["halfplot"]],
        rsmplot = function() private$.items[["rsmplot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="2k Experimental Design")
            self$add(jmvcore::Html$new(
                options=options,
                name="description",
                title="description",
                visible="(showdescription)"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="doetable",
                title="Experimental and Predicted Responses Table"))
            self$add(jmvcore::Table$new(
                options=options,
                name="doetable2",
                title="Experimental Design Table",
                columns=list()))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="doeanova",
                title="ANOVA Table"))
            self$add(jmvcore::Table$new(
                options=options,
                name="anovatable",
                title="`Analysis of Variance Table - Response: ${yield}`",
                columns=list()))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="estitabletitleX",
                title="Coded Model Parameter Estimation Table"))
            self$add(jmvcore::Table$new(
                options=options,
                name="estitableX",
                title="Coded Parameter Estimation Table",
                columns=list()))
            self$add(jmvcore::Table$new(
                options=options,
                name="maintable",
                title="`Coded Model - ${yield}`",
                rows=1,
                columns=list(
                    list(
                        `name`="equ1", 
                        `title`="Model equation (Coded)", 
                        `type`="text"),
                    list(
                        `name`="Rsq1", 
                        `title`="R<sup>2</sup>", 
                        `type`="number"),
                    list(
                        `name`="Ad1", 
                        `title`="R<sub>A</sub><sup>2</sup>", 
                        `type`="number"),
                    list(
                        `name`="Mse1", 
                        `title`="MSE", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="maintable3kCoded",
                title="`Coded 2\u1D4F Model splitted by categories - ${yield}`",
                rows=2,
                visible="(cats)",
                columns=list(
                    list(
                        `name`="ccox3", 
                        `title`="Splitted Coded Model Equation", 
                        `type`="text"))))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="scalingtitle",
                title="Scaling Table"))
            self$add(jmvcore::Table$new(
                options=options,
                name="scalingtable",
                title="Scaling Table",
                columns=list()))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="estitabletitle",
                title="Model Parameter Estimation Table"))
            self$add(jmvcore::Table$new(
                options=options,
                name="estitableOR",
                title="Original Parameter Estimation Table",
                columns=list()))
            self$add(jmvcore::Table$new(
                options=options,
                name="maintable2",
                title="`Model - ${yield}`",
                rows=1,
                columns=list(
                    list(
                        `name`="equ2", 
                        `title`="Model Equation", 
                        `type`="text"),
                    list(
                        `name`="Rsq2", 
                        `title`="R<sup>2</sup>", 
                        `type`="number"),
                    list(
                        `name`="Ad2", 
                        `title`="R<sub>A</sub><sup>2</sup>", 
                        `type`="number"),
                    list(
                        `name`="Mse2", 
                        `title`="MSE", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="maintable3k",
                title="`2\u1D4F Model splitted by categories - ${yield}`",
                rows=2,
                visible="(cats)",
                columns=list(
                    list(
                        `name`="cox3", 
                        `title`="Splitted Model Equation", 
                        `type`="text"))))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="doedataset"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="cols"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="rsmformula"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="showplot"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="modellm"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="modelrsm"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="colsrsm"))
            self$add(jmvcore::Image$new(
                options=options,
                name="mainplot",
                title="Main Effects Plot",
                width=960,
                height=480,
                renderFun=".mainplot",
                requiresData=TRUE,
                visible="(showeffects)"))
            self$add(jmvcore::Image$new(
                options=options,
                name="interactionplot",
                title="Interaction Plot",
                width=960,
                height=480,
                renderFun=".interactionplot",
                requiresData=TRUE,
                visible="(showinteraction)"))
            self$add(jmvcore::Image$new(
                options=options,
                name="paretoplot",
                title="Pareto Plot",
                width=640,
                height=320,
                renderFun=".paretoplot",
                requiresData=TRUE,
                visible="(showpareto)"))
            self$add(jmvcore::Image$new(
                options=options,
                name="halfplot",
                title="Half-Normal Plot",
                width=640,
                height=320,
                renderFun=".halfplot",
                requiresData=TRUE,
                visible="(showhalf)"))
            self$add(jmvcore::Image$new(
                options=options,
                name="rsmplot",
                title="Response Surface Plots",
                width=960,
                height=1280,
                renderFun=".rsmplot",
                requiresData=TRUE,
                visible="(showrsm)"))}))

designkmodelBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "designkmodelBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "FoodieStats",
                name = "designkmodel",
                version = c(1,0,0),
                options = options,
                results = designkmodelResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' 2k Experimental Design
#'
#' 
#' @param data .
#' @param showdescription .
#' @param yield .
#' @param vars .
#' @param cats .
#' @param alphaval .
#' @param showeffects .
#' @param showinteraction .
#' @param showpareto .
#' @param showhalf .
#' @param criteria .
#' @param mupdate .
#' @param showrsm .
#' @param thetaval .
#' @param phival .
#' @param colorselection .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$description} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$doetable} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$doetable2} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$doeanova} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$anovatable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$estitabletitleX} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$estitableX} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$maintable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$maintable3kCoded} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$scalingtitle} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$scalingtable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$estitabletitle} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$estitableOR} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$maintable2} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$maintable3k} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$doedataset} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$cols} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$rsmformula} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$showplot} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$modellm} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$modelrsm} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$colsrsm} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$mainplot} \tab \tab \tab \tab \tab the main effects plot \cr
#'   \code{results$interactionplot} \tab \tab \tab \tab \tab an interaction plot \cr
#'   \code{results$paretoplot} \tab \tab \tab \tab \tab pareto plot \cr
#'   \code{results$halfplot} \tab \tab \tab \tab \tab Half-Normal plot \cr
#'   \code{results$rsmplot} \tab \tab \tab \tab \tab Response Surface plot \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$doetable2$asDF}
#'
#' \code{as.data.frame(results$doetable2)}
#'
#' @export
designkmodel <- function(
    data,
    showdescription = FALSE,
    yield,
    vars,
    cats,
    alphaval = 5,
    showeffects = FALSE,
    showinteraction = FALSE,
    showpareto = FALSE,
    showhalf = FALSE,
    criteria = "Lenth",
    mupdate = "default",
    showrsm = FALSE,
    thetaval = -25,
    phival = 20,
    colorselection = "SpectralStylish") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("designkmodel requires jmvcore to be installed (restart may be required)")

    if ( ! missing(yield)) yield <- jmvcore::resolveQuo(jmvcore::enquo(yield))
    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if ( ! missing(cats)) cats <- jmvcore::resolveQuo(jmvcore::enquo(cats))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(yield), yield, NULL),
            `if`( ! missing(vars), vars, NULL),
            `if`( ! missing(cats), cats, NULL))

    for (v in vars) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in cats) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- designkmodelOptions$new(
        showdescription = showdescription,
        yield = yield,
        vars = vars,
        cats = cats,
        alphaval = alphaval,
        showeffects = showeffects,
        showinteraction = showinteraction,
        showpareto = showpareto,
        showhalf = showhalf,
        criteria = criteria,
        mupdate = mupdate,
        showrsm = showrsm,
        thetaval = thetaval,
        phival = phival,
        colorselection = colorselection)

    analysis <- designkmodelClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

