
# This file is automatically generated, you probably don't want to edit this

designrsmmodelOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "designrsmmodelOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            showdescription = FALSE,
            yield = NULL,
            vars = NULL,
            rsdesign = "bbd",
            alphaval = 5,
            showeffects = FALSE,
            showinteraction = FALSE,
            showpareto = FALSE,
            mupdate = "default",
            showrsm = FALSE,
            thetaval = -25,
            phival = 20, ...) {

            super$initialize(
                package="FoodieStats",
                name="designrsmmodel",
                requiresData=TRUE,
                ...)

            private$..showdescription <- jmvcore::OptionBool$new(
                "showdescription",
                showdescription,
                default=FALSE)
            private$..yield <- jmvcore::OptionVariable$new(
                "yield",
                yield,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..rsdesign <- jmvcore::OptionList$new(
                "rsdesign",
                rsdesign,
                options=list(
                    "bbd",
                    "ccc",
                    "cci",
                    "ccf"),
                default="bbd")
            private$..alphaval <- jmvcore::OptionNumber$new(
                "alphaval",
                alphaval,
                default=5,
                min=1,
                max=25)
            private$..showeffects <- jmvcore::OptionBool$new(
                "showeffects",
                showeffects,
                default=FALSE)
            private$..showinteraction <- jmvcore::OptionBool$new(
                "showinteraction",
                showinteraction,
                default=FALSE)
            private$..showpareto <- jmvcore::OptionBool$new(
                "showpareto",
                showpareto,
                default=FALSE)
            private$..mupdate <- jmvcore::OptionList$new(
                "mupdate",
                mupdate,
                options=list(
                    "default",
                    "forward",
                    "backward",
                    "both",
                    "backwardalpha",
                    "allin"),
                default="default")
            private$..showrsm <- jmvcore::OptionBool$new(
                "showrsm",
                showrsm,
                default=FALSE)
            private$..thetaval <- jmvcore::OptionNumber$new(
                "thetaval",
                thetaval,
                default=-25,
                min=-180,
                max=180)
            private$..phival <- jmvcore::OptionNumber$new(
                "phival",
                phival,
                default=20,
                min=-180,
                max=180)

            self$.addOption(private$..showdescription)
            self$.addOption(private$..yield)
            self$.addOption(private$..vars)
            self$.addOption(private$..rsdesign)
            self$.addOption(private$..alphaval)
            self$.addOption(private$..showeffects)
            self$.addOption(private$..showinteraction)
            self$.addOption(private$..showpareto)
            self$.addOption(private$..mupdate)
            self$.addOption(private$..showrsm)
            self$.addOption(private$..thetaval)
            self$.addOption(private$..phival)
        }),
    active = list(
        showdescription = function() private$..showdescription$value,
        yield = function() private$..yield$value,
        vars = function() private$..vars$value,
        rsdesign = function() private$..rsdesign$value,
        alphaval = function() private$..alphaval$value,
        showeffects = function() private$..showeffects$value,
        showinteraction = function() private$..showinteraction$value,
        showpareto = function() private$..showpareto$value,
        mupdate = function() private$..mupdate$value,
        showrsm = function() private$..showrsm$value,
        thetaval = function() private$..thetaval$value,
        phival = function() private$..phival$value),
    private = list(
        ..showdescription = NA,
        ..yield = NA,
        ..vars = NA,
        ..rsdesign = NA,
        ..alphaval = NA,
        ..showeffects = NA,
        ..showinteraction = NA,
        ..showpareto = NA,
        ..mupdate = NA,
        ..showrsm = NA,
        ..thetaval = NA,
        ..phival = NA)
)

designrsmmodelResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "designrsmmodelResults",
    inherit = jmvcore::Group,
    active = list(
        description = function() private$.items[["description"]],
        doetable = function() private$.items[["doetable"]],
        doetable2 = function() private$.items[["doetable2"]],
        doeanova = function() private$.items[["doeanova"]],
        designcoded = function() private$.items[["designcoded"]],
        maintable = function() private$.items[["maintable"]],
        designuncoded = function() private$.items[["designuncoded"]],
        maintable2 = function() private$.items[["maintable2"]],
        doedataset = function() private$.items[["doedataset"]],
        cols = function() private$.items[["cols"]],
        paretodata = function() private$.items[["paretodata"]],
        modelrsm = function() private$.items[["modelrsm"]],
        colsrsm = function() private$.items[["colsrsm"]],
        mainplot = function() private$.items[["mainplot"]],
        interactionplot = function() private$.items[["interactionplot"]],
        paretoplot = function() private$.items[["paretoplot"]],
        rsmplot = function() private$.items[["rsmplot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Response Surface Design")
            self$add(jmvcore::Html$new(
                options=options,
                name="description",
                title="description",
                visible="(showdescription)"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="doetable",
                title="Experimental and Predicted Responses Table"))
            self$add(jmvcore::Table$new(
                options=options,
                name="doetable2",
                title="Experimental Design Table",
                columns=list()))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="doeanova",
                title="ANOVA Table"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="designcoded",
                title="Model prediction (Coded)"))
            self$add(jmvcore::Table$new(
                options=options,
                name="maintable",
                title="`Coded Model - ${yield}`",
                rows=1,
                columns=list(
                    list(
                        `name`="equ1", 
                        `title`="Model equation (Coded)", 
                        `type`="text"),
                    list(
                        `name`="Rsq1", 
                        `title`="Multiple R-Squared", 
                        `type`="number"),
                    list(
                        `name`="Ad1", 
                        `title`="Adjusted R-Squared", 
                        `type`="number"))))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="designuncoded",
                title="Model prediction (Uncoded)"))
            self$add(jmvcore::Table$new(
                options=options,
                name="maintable2",
                title="`Uncoded Model - ${yield}`",
                rows=1,
                columns=list(
                    list(
                        `name`="equ2", 
                        `title`="Model equation (Uncoded)", 
                        `type`="text"),
                    list(
                        `name`="Rsq2", 
                        `title`="Multiple R-Squared", 
                        `type`="number"),
                    list(
                        `name`="Ad2", 
                        `title`="Adjusted R-Squared", 
                        `type`="number"))))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="doedataset"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="cols"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="paretodata"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="modelrsm"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="colsrsm"))
            self$add(jmvcore::Image$new(
                options=options,
                name="mainplot",
                title="Main Effects Plot",
                width=960,
                height=480,
                renderFun=".mainplot",
                requiresData=TRUE,
                visible="(showeffects)"))
            self$add(jmvcore::Image$new(
                options=options,
                name="interactionplot",
                title="Interaction Plot",
                width=960,
                height=480,
                renderFun=".interactionplot",
                requiresData=TRUE,
                visible="(showinteraction)"))
            self$add(jmvcore::Image$new(
                options=options,
                name="paretoplot",
                title="Pareto Plot",
                width=640,
                height=320,
                renderFun=".paretoplot",
                requiresData=TRUE,
                visible="(showpareto)"))
            self$add(jmvcore::Image$new(
                options=options,
                name="rsmplot",
                title="Response Surface Plots",
                width=960,
                height=1280,
                renderFun=".rsmplot",
                requiresData=TRUE,
                visible="(showrsm)"))}))

designrsmmodelBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "designrsmmodelBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "FoodieStats",
                name = "designrsmmodel",
                version = c(1,0,0),
                options = options,
                results = designrsmmodelResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Response Surface Design
#'
#' 
#' @param data .
#' @param showdescription .
#' @param yield .
#' @param vars .
#' @param rsdesign .
#' @param alphaval .
#' @param showeffects .
#' @param showinteraction .
#' @param showpareto .
#' @param mupdate .
#' @param showrsm .
#' @param thetaval .
#' @param phival .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$description} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$doetable} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$doetable2} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$doeanova} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$designcoded} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$maintable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$designuncoded} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$maintable2} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$doedataset} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$cols} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$paretodata} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$modelrsm} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$colsrsm} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$mainplot} \tab \tab \tab \tab \tab the main effects plot \cr
#'   \code{results$interactionplot} \tab \tab \tab \tab \tab an interaction plot \cr
#'   \code{results$paretoplot} \tab \tab \tab \tab \tab pareto plot \cr
#'   \code{results$rsmplot} \tab \tab \tab \tab \tab Response Surface plot \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$doetable2$asDF}
#'
#' \code{as.data.frame(results$doetable2)}
#'
#' @export
designrsmmodel <- function(
    data,
    showdescription = FALSE,
    yield,
    vars,
    rsdesign = "bbd",
    alphaval = 5,
    showeffects = FALSE,
    showinteraction = FALSE,
    showpareto = FALSE,
    mupdate = "default",
    showrsm = FALSE,
    thetaval = -25,
    phival = 20) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("designrsmmodel requires jmvcore to be installed (restart may be required)")

    if ( ! missing(yield)) yield <- jmvcore::resolveQuo(jmvcore::enquo(yield))
    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(yield), yield, NULL),
            `if`( ! missing(vars), vars, NULL))

    for (v in vars) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- designrsmmodelOptions$new(
        showdescription = showdescription,
        yield = yield,
        vars = vars,
        rsdesign = rsdesign,
        alphaval = alphaval,
        showeffects = showeffects,
        showinteraction = showinteraction,
        showpareto = showpareto,
        mupdate = mupdate,
        showrsm = showrsm,
        thetaval = thetaval,
        phival = phival)

    analysis <- designrsmmodelClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

