
# This file is automatically generated, you probably don't want to edit this

desirabilityOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "desirabilityOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            showdescription = FALSE,
            vars = NULL,
            d1yield = NULL,
            d1modelinfo = NULL,
            d1type = "dNone",
            d1low = 0,
            d1high = 10,
            d1target = 5,
            d2yield = NULL,
            d2modelinfo = NULL,
            d2type = "dNone",
            d2low = 0,
            d2high = 10,
            d2target = 5,
            d3yield = NULL,
            d3modelinfo = NULL,
            d3type = "dNone",
            d3low = 0,
            d3high = 10,
            d3target = 5,
            d4yield = NULL,
            d4modelinfo = NULL,
            d4type = "dNone",
            d4low = 0,
            d4high = 10,
            d4target = 5,
            d5yield = NULL,
            d5modelinfo = NULL,
            d5type = "dNone",
            d5low = 0,
            d5high = 10,
            d5target = 5,
            showoverall = FALSE,
            showindividuals = FALSE,
            thetaval = -25,
            phival = 20,
            colorselection = "SpectralStylish",
            latentvar = "1",
            latentplane = "0", ...) {

            super$initialize(
                package="FoodieStats",
                name="desirability",
                requiresData=TRUE,
                ...)

            private$..showdescription <- jmvcore::OptionBool$new(
                "showdescription",
                showdescription,
                default=FALSE)
            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..d1yield <- jmvcore::OptionVariable$new(
                "d1yield",
                d1yield,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..d1modelinfo <- jmvcore::OptionVariable$new(
                "d1modelinfo",
                d1modelinfo,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..d1type <- jmvcore::OptionList$new(
                "d1type",
                d1type,
                options=list(
                    "dNone",
                    "dMax",
                    "dMin",
                    "dTarget"),
                default="dNone")
            private$..d1low <- jmvcore::OptionNumber$new(
                "d1low",
                d1low,
                default=0)
            private$..d1high <- jmvcore::OptionNumber$new(
                "d1high",
                d1high,
                default=10)
            private$..d1target <- jmvcore::OptionNumber$new(
                "d1target",
                d1target,
                default=5)
            private$..d2yield <- jmvcore::OptionVariable$new(
                "d2yield",
                d2yield,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..d2modelinfo <- jmvcore::OptionVariable$new(
                "d2modelinfo",
                d2modelinfo,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..d2type <- jmvcore::OptionList$new(
                "d2type",
                d2type,
                options=list(
                    "dNone",
                    "dMax",
                    "dMin",
                    "dTarget"),
                default="dNone")
            private$..d2low <- jmvcore::OptionNumber$new(
                "d2low",
                d2low,
                default=0)
            private$..d2high <- jmvcore::OptionNumber$new(
                "d2high",
                d2high,
                default=10)
            private$..d2target <- jmvcore::OptionNumber$new(
                "d2target",
                d2target,
                default=5)
            private$..d3yield <- jmvcore::OptionVariable$new(
                "d3yield",
                d3yield,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..d3modelinfo <- jmvcore::OptionVariable$new(
                "d3modelinfo",
                d3modelinfo,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..d3type <- jmvcore::OptionList$new(
                "d3type",
                d3type,
                options=list(
                    "dNone",
                    "dMax",
                    "dMin",
                    "dTarget"),
                default="dNone")
            private$..d3low <- jmvcore::OptionNumber$new(
                "d3low",
                d3low,
                default=0)
            private$..d3high <- jmvcore::OptionNumber$new(
                "d3high",
                d3high,
                default=10)
            private$..d3target <- jmvcore::OptionNumber$new(
                "d3target",
                d3target,
                default=5)
            private$..d4yield <- jmvcore::OptionVariable$new(
                "d4yield",
                d4yield,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..d4modelinfo <- jmvcore::OptionVariable$new(
                "d4modelinfo",
                d4modelinfo,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..d4type <- jmvcore::OptionList$new(
                "d4type",
                d4type,
                options=list(
                    "dNone",
                    "dMax",
                    "dMin",
                    "dTarget"),
                default="dNone")
            private$..d4low <- jmvcore::OptionNumber$new(
                "d4low",
                d4low,
                default=0)
            private$..d4high <- jmvcore::OptionNumber$new(
                "d4high",
                d4high,
                default=10)
            private$..d4target <- jmvcore::OptionNumber$new(
                "d4target",
                d4target,
                default=5)
            private$..d5yield <- jmvcore::OptionVariable$new(
                "d5yield",
                d5yield,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..d5modelinfo <- jmvcore::OptionVariable$new(
                "d5modelinfo",
                d5modelinfo,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..d5type <- jmvcore::OptionList$new(
                "d5type",
                d5type,
                options=list(
                    "dNone",
                    "dMax",
                    "dMin",
                    "dTarget"),
                default="dNone")
            private$..d5low <- jmvcore::OptionNumber$new(
                "d5low",
                d5low,
                default=0)
            private$..d5high <- jmvcore::OptionNumber$new(
                "d5high",
                d5high,
                default=10)
            private$..d5target <- jmvcore::OptionNumber$new(
                "d5target",
                d5target,
                default=5)
            private$..showoverall <- jmvcore::OptionBool$new(
                "showoverall",
                showoverall,
                default=FALSE)
            private$..showindividuals <- jmvcore::OptionBool$new(
                "showindividuals",
                showindividuals,
                default=FALSE)
            private$..thetaval <- jmvcore::OptionNumber$new(
                "thetaval",
                thetaval,
                default=-25,
                min=-180,
                max=180)
            private$..phival <- jmvcore::OptionNumber$new(
                "phival",
                phival,
                default=20,
                min=-180,
                max=180)
            private$..colorselection <- jmvcore::OptionList$new(
                "colorselection",
                colorselection,
                options=list(
                    "SpectralStylish",
                    "JamoviStylish",
                    "BeachStylish",
                    "OceanStylish",
                    "Market",
                    "Gingerbread",
                    "Umami",
                    "SummerSalad",
                    "FruitCup",
                    "Delight",
                    "Greensmoothie",
                    "Turmeric",
                    "Snacks",
                    "Sashimi",
                    "Macarons",
                    "Feast",
                    "Veggies",
                    "Beetroot",
                    "Spice",
                    "Sweet",
                    "Tropical",
                    "Breakfast",
                    "Carrots",
                    "Stick",
                    "Tea",
                    "Decadent",
                    "Berry",
                    "Sugary",
                    "Citrus",
                    "Chard",
                    "Shrimp",
                    "SweetSalad",
                    "Cheesecake",
                    "FruitBasket",
                    "Cayenne",
                    "Smoothie",
                    "Mojito",
                    "Coffee",
                    "Wine",
                    "Beer",
                    "Fish",
                    "Cheese",
                    "Bread",
                    "Chocolate",
                    "Beef",
                    "Honey",
                    "Dairy",
                    "Vegetables",
                    "Bean",
                    "Seafood",
                    "Octopus"),
                default="SpectralStylish")
            private$..latentvar <- jmvcore::OptionList$new(
                "latentvar",
                latentvar,
                options=list(
                    "1",
                    "2",
                    "3",
                    "4"),
                default="1")
            private$..latentplane <- jmvcore::OptionList$new(
                "latentplane",
                latentplane,
                options=list(
                    "0",
                    "0.1",
                    "0.2",
                    "0.3",
                    "0.4",
                    "0.5",
                    "0.6",
                    "0.7",
                    "0.8"),
                default="0")

            self$.addOption(private$..showdescription)
            self$.addOption(private$..vars)
            self$.addOption(private$..d1yield)
            self$.addOption(private$..d1modelinfo)
            self$.addOption(private$..d1type)
            self$.addOption(private$..d1low)
            self$.addOption(private$..d1high)
            self$.addOption(private$..d1target)
            self$.addOption(private$..d2yield)
            self$.addOption(private$..d2modelinfo)
            self$.addOption(private$..d2type)
            self$.addOption(private$..d2low)
            self$.addOption(private$..d2high)
            self$.addOption(private$..d2target)
            self$.addOption(private$..d3yield)
            self$.addOption(private$..d3modelinfo)
            self$.addOption(private$..d3type)
            self$.addOption(private$..d3low)
            self$.addOption(private$..d3high)
            self$.addOption(private$..d3target)
            self$.addOption(private$..d4yield)
            self$.addOption(private$..d4modelinfo)
            self$.addOption(private$..d4type)
            self$.addOption(private$..d4low)
            self$.addOption(private$..d4high)
            self$.addOption(private$..d4target)
            self$.addOption(private$..d5yield)
            self$.addOption(private$..d5modelinfo)
            self$.addOption(private$..d5type)
            self$.addOption(private$..d5low)
            self$.addOption(private$..d5high)
            self$.addOption(private$..d5target)
            self$.addOption(private$..showoverall)
            self$.addOption(private$..showindividuals)
            self$.addOption(private$..thetaval)
            self$.addOption(private$..phival)
            self$.addOption(private$..colorselection)
            self$.addOption(private$..latentvar)
            self$.addOption(private$..latentplane)
        }),
    active = list(
        showdescription = function() private$..showdescription$value,
        vars = function() private$..vars$value,
        d1yield = function() private$..d1yield$value,
        d1modelinfo = function() private$..d1modelinfo$value,
        d1type = function() private$..d1type$value,
        d1low = function() private$..d1low$value,
        d1high = function() private$..d1high$value,
        d1target = function() private$..d1target$value,
        d2yield = function() private$..d2yield$value,
        d2modelinfo = function() private$..d2modelinfo$value,
        d2type = function() private$..d2type$value,
        d2low = function() private$..d2low$value,
        d2high = function() private$..d2high$value,
        d2target = function() private$..d2target$value,
        d3yield = function() private$..d3yield$value,
        d3modelinfo = function() private$..d3modelinfo$value,
        d3type = function() private$..d3type$value,
        d3low = function() private$..d3low$value,
        d3high = function() private$..d3high$value,
        d3target = function() private$..d3target$value,
        d4yield = function() private$..d4yield$value,
        d4modelinfo = function() private$..d4modelinfo$value,
        d4type = function() private$..d4type$value,
        d4low = function() private$..d4low$value,
        d4high = function() private$..d4high$value,
        d4target = function() private$..d4target$value,
        d5yield = function() private$..d5yield$value,
        d5modelinfo = function() private$..d5modelinfo$value,
        d5type = function() private$..d5type$value,
        d5low = function() private$..d5low$value,
        d5high = function() private$..d5high$value,
        d5target = function() private$..d5target$value,
        showoverall = function() private$..showoverall$value,
        showindividuals = function() private$..showindividuals$value,
        thetaval = function() private$..thetaval$value,
        phival = function() private$..phival$value,
        colorselection = function() private$..colorselection$value,
        latentvar = function() private$..latentvar$value,
        latentplane = function() private$..latentplane$value),
    private = list(
        ..showdescription = NA,
        ..vars = NA,
        ..d1yield = NA,
        ..d1modelinfo = NA,
        ..d1type = NA,
        ..d1low = NA,
        ..d1high = NA,
        ..d1target = NA,
        ..d2yield = NA,
        ..d2modelinfo = NA,
        ..d2type = NA,
        ..d2low = NA,
        ..d2high = NA,
        ..d2target = NA,
        ..d3yield = NA,
        ..d3modelinfo = NA,
        ..d3type = NA,
        ..d3low = NA,
        ..d3high = NA,
        ..d3target = NA,
        ..d4yield = NA,
        ..d4modelinfo = NA,
        ..d4type = NA,
        ..d4low = NA,
        ..d4high = NA,
        ..d4target = NA,
        ..d5yield = NA,
        ..d5modelinfo = NA,
        ..d5type = NA,
        ..d5low = NA,
        ..d5high = NA,
        ..d5target = NA,
        ..showoverall = NA,
        ..showindividuals = NA,
        ..thetaval = NA,
        ..phival = NA,
        ..colorselection = NA,
        ..latentvar = NA,
        ..latentplane = NA)
)

desirabilityResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "desirabilityResults",
    inherit = jmvcore::Group,
    active = list(
        description = function() private$.items[["description"]],
        doetable = function() private$.items[["doetable"]],
        doetable2 = function() private$.items[["doetable2"]],
        designuncoded = function() private$.items[["designuncoded"]],
        scalingtable = function() private$.items[["scalingtable"]],
        designcoded = function() private$.items[["designcoded"]],
        desitable1 = function() private$.items[["desitable1"]],
        desitable2 = function() private$.items[["desitable2"]],
        desitable3 = function() private$.items[["desitable3"]],
        optpoint = function() private$.items[["optpoint"]],
        ternarydata = function() private$.items[["ternarydata"]],
        desirabilitydata = function() private$.items[["desirabilitydata"]],
        desirabilitymodels = function() private$.items[["desirabilitymodels"]],
        desiresponse = function() private$.items[["desiresponse"]],
        overall4kplot = function() private$.items[["overall4kplot"]],
        individual4kplot = function() private$.items[["individual4kplot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Desirability Optimization")
            self$add(jmvcore::Html$new(
                options=options,
                name="description",
                title="description",
                visible="(showdescription)"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="doetable",
                title="Experimental Table"))
            self$add(jmvcore::Table$new(
                options=options,
                name="doetable2",
                title="Experimental Optimization Table (original values, mixture proportions and multiple responses)",
                columns=list()))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="designuncoded",
                title="Mixture Proportions"))
            self$add(jmvcore::Table$new(
                options=options,
                name="scalingtable",
                title="Mixture Scaling Table",
                columns=list()))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="designcoded",
                title="Desirability Optimization Table"))
            self$add(jmvcore::Table$new(
                options=options,
                name="desitable1",
                title="Optimal Point Coordinates (original values and mixture proportions)",
                columns=list()))
            self$add(jmvcore::Table$new(
                options=options,
                name="desitable2",
                title="Desirability Values at Optimal Point",
                columns=list()))
            self$add(jmvcore::Table$new(
                options=options,
                name="desitable3",
                title="Prediction Values at Optimal Point",
                columns=list()))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="optpoint"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="ternarydata"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="desirabilitydata"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="desirabilitymodels"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="desiresponse"))
            self$add(jmvcore::Image$new(
                options=options,
                name="overall4kplot",
                title="Overall Desirability Plot (mixture proportions)",
                width=960,
                height=480,
                renderFun=".overall4kplot",
                requiresData=TRUE,
                visible="(showoverall)"))
            self$add(jmvcore::Image$new(
                options=options,
                name="individual4kplot",
                title="Individual Desirability Plots (mixture proportions)",
                width=960,
                height=480,
                renderFun=".individual4kplot",
                requiresData=TRUE,
                visible="(showindividuals)"))}))

desirabilityBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "desirabilityBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "FoodieStats",
                name = "desirability",
                version = c(1,0,0),
                options = options,
                results = desirabilityResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Desirability Optimization
#'
#' 
#' @param data .
#' @param showdescription .
#' @param vars .
#' @param d1yield .
#' @param d1modelinfo .
#' @param d1type .
#' @param d1low .
#' @param d1high .
#' @param d1target .
#' @param d2yield .
#' @param d2modelinfo .
#' @param d2type .
#' @param d2low .
#' @param d2high .
#' @param d2target .
#' @param d3yield .
#' @param d3modelinfo .
#' @param d3type .
#' @param d3low .
#' @param d3high .
#' @param d3target .
#' @param d4yield .
#' @param d4modelinfo .
#' @param d4type .
#' @param d4low .
#' @param d4high .
#' @param d4target .
#' @param d5yield .
#' @param d5modelinfo .
#' @param d5type .
#' @param d5low .
#' @param d5high .
#' @param d5target .
#' @param showoverall .
#' @param showindividuals .
#' @param thetaval .
#' @param phival .
#' @param colorselection .
#' @param latentvar .
#' @param latentplane .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$description} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$doetable} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$doetable2} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$designuncoded} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$scalingtable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$designcoded} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$desitable1} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$desitable2} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$desitable3} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$optpoint} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$ternarydata} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$desirabilitydata} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$desirabilitymodels} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$desiresponse} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$overall4kplot} \tab \tab \tab \tab \tab Desirability plot for 3 and 4 variables \cr
#'   \code{results$individual4kplot} \tab \tab \tab \tab \tab Individual Desirability Plots for 3 and 4 variables \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$doetable2$asDF}
#'
#' \code{as.data.frame(results$doetable2)}
#'
#' @export
desirability <- function(
    data,
    showdescription = FALSE,
    vars,
    d1yield,
    d1modelinfo,
    d1type = "dNone",
    d1low = 0,
    d1high = 10,
    d1target = 5,
    d2yield,
    d2modelinfo,
    d2type = "dNone",
    d2low = 0,
    d2high = 10,
    d2target = 5,
    d3yield,
    d3modelinfo,
    d3type = "dNone",
    d3low = 0,
    d3high = 10,
    d3target = 5,
    d4yield,
    d4modelinfo,
    d4type = "dNone",
    d4low = 0,
    d4high = 10,
    d4target = 5,
    d5yield,
    d5modelinfo,
    d5type = "dNone",
    d5low = 0,
    d5high = 10,
    d5target = 5,
    showoverall = FALSE,
    showindividuals = FALSE,
    thetaval = -25,
    phival = 20,
    colorselection = "SpectralStylish",
    latentvar = "1",
    latentplane = "0") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("desirability requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if ( ! missing(d1yield)) d1yield <- jmvcore::resolveQuo(jmvcore::enquo(d1yield))
    if ( ! missing(d1modelinfo)) d1modelinfo <- jmvcore::resolveQuo(jmvcore::enquo(d1modelinfo))
    if ( ! missing(d2yield)) d2yield <- jmvcore::resolveQuo(jmvcore::enquo(d2yield))
    if ( ! missing(d2modelinfo)) d2modelinfo <- jmvcore::resolveQuo(jmvcore::enquo(d2modelinfo))
    if ( ! missing(d3yield)) d3yield <- jmvcore::resolveQuo(jmvcore::enquo(d3yield))
    if ( ! missing(d3modelinfo)) d3modelinfo <- jmvcore::resolveQuo(jmvcore::enquo(d3modelinfo))
    if ( ! missing(d4yield)) d4yield <- jmvcore::resolveQuo(jmvcore::enquo(d4yield))
    if ( ! missing(d4modelinfo)) d4modelinfo <- jmvcore::resolveQuo(jmvcore::enquo(d4modelinfo))
    if ( ! missing(d5yield)) d5yield <- jmvcore::resolveQuo(jmvcore::enquo(d5yield))
    if ( ! missing(d5modelinfo)) d5modelinfo <- jmvcore::resolveQuo(jmvcore::enquo(d5modelinfo))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL),
            `if`( ! missing(d1yield), d1yield, NULL),
            `if`( ! missing(d1modelinfo), d1modelinfo, NULL),
            `if`( ! missing(d2yield), d2yield, NULL),
            `if`( ! missing(d2modelinfo), d2modelinfo, NULL),
            `if`( ! missing(d3yield), d3yield, NULL),
            `if`( ! missing(d3modelinfo), d3modelinfo, NULL),
            `if`( ! missing(d4yield), d4yield, NULL),
            `if`( ! missing(d4modelinfo), d4modelinfo, NULL),
            `if`( ! missing(d5yield), d5yield, NULL),
            `if`( ! missing(d5modelinfo), d5modelinfo, NULL))

    for (v in vars) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in d1modelinfo) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in d2modelinfo) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in d3modelinfo) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in d4modelinfo) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in d5modelinfo) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- desirabilityOptions$new(
        showdescription = showdescription,
        vars = vars,
        d1yield = d1yield,
        d1modelinfo = d1modelinfo,
        d1type = d1type,
        d1low = d1low,
        d1high = d1high,
        d1target = d1target,
        d2yield = d2yield,
        d2modelinfo = d2modelinfo,
        d2type = d2type,
        d2low = d2low,
        d2high = d2high,
        d2target = d2target,
        d3yield = d3yield,
        d3modelinfo = d3modelinfo,
        d3type = d3type,
        d3low = d3low,
        d3high = d3high,
        d3target = d3target,
        d4yield = d4yield,
        d4modelinfo = d4modelinfo,
        d4type = d4type,
        d4low = d4low,
        d4high = d4high,
        d4target = d4target,
        d5yield = d5yield,
        d5modelinfo = d5modelinfo,
        d5type = d5type,
        d5low = d5low,
        d5high = d5high,
        d5target = d5target,
        showoverall = showoverall,
        showindividuals = showindividuals,
        thetaval = thetaval,
        phival = phival,
        colorselection = colorselection,
        latentvar = latentvar,
        latentplane = latentplane)

    analysis <- desirabilityClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

