
# This file is automatically generated, you probably don't want to edit this

JARScalesOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "JARScalesOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            attr = NULL,
            attrscale = "Five",
            lik = NULL,
            threshold = 20,
            mdropthreshold = 1,
            posthoc = TRUE,
            posthocalpha = 95,
            attrhoc = TRUE,
            attrhocalpha = 95,
            showbarras = FALSE,
            showternary = FALSE,
            showdiagnose = FALSE, ...) {

            super$initialize(
                package="FoodieStats",
                name="JARScales",
                requiresData=TRUE,
                ...)

            private$..attr <- jmvcore::OptionVariables$new(
                "attr",
                attr,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..attrscale <- jmvcore::OptionList$new(
                "attrscale",
                attrscale,
                options=list(
                    "Three",
                    "Five",
                    "Seven",
                    "Nine"),
                default="Five")
            private$..lik <- jmvcore::OptionVariable$new(
                "lik",
                lik,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..threshold <- jmvcore::OptionNumber$new(
                "threshold",
                threshold,
                default=20,
                min=1,
                max=99)
            private$..mdropthreshold <- jmvcore::OptionNumber$new(
                "mdropthreshold",
                mdropthreshold,
                default=1,
                min=0,
                max=10)
            private$..posthoc <- jmvcore::OptionBool$new(
                "posthoc",
                posthoc,
                default=TRUE)
            private$..posthocalpha <- jmvcore::OptionNumber$new(
                "posthocalpha",
                posthocalpha,
                default=95,
                min=1,
                max=99)
            private$..attrhoc <- jmvcore::OptionBool$new(
                "attrhoc",
                attrhoc,
                default=TRUE)
            private$..attrhocalpha <- jmvcore::OptionNumber$new(
                "attrhocalpha",
                attrhocalpha,
                default=95,
                min=1,
                max=99)
            private$..showbarras <- jmvcore::OptionBool$new(
                "showbarras",
                showbarras,
                default=FALSE)
            private$..showternary <- jmvcore::OptionBool$new(
                "showternary",
                showternary,
                default=FALSE)
            private$..showdiagnose <- jmvcore::OptionBool$new(
                "showdiagnose",
                showdiagnose,
                default=FALSE)

            self$.addOption(private$..attr)
            self$.addOption(private$..attrscale)
            self$.addOption(private$..lik)
            self$.addOption(private$..threshold)
            self$.addOption(private$..mdropthreshold)
            self$.addOption(private$..posthoc)
            self$.addOption(private$..posthocalpha)
            self$.addOption(private$..attrhoc)
            self$.addOption(private$..attrhocalpha)
            self$.addOption(private$..showbarras)
            self$.addOption(private$..showternary)
            self$.addOption(private$..showdiagnose)
        }),
    active = list(
        attr = function() private$..attr$value,
        attrscale = function() private$..attrscale$value,
        lik = function() private$..lik$value,
        threshold = function() private$..threshold$value,
        mdropthreshold = function() private$..mdropthreshold$value,
        posthoc = function() private$..posthoc$value,
        posthocalpha = function() private$..posthocalpha$value,
        attrhoc = function() private$..attrhoc$value,
        attrhocalpha = function() private$..attrhocalpha$value,
        showbarras = function() private$..showbarras$value,
        showternary = function() private$..showternary$value,
        showdiagnose = function() private$..showdiagnose$value),
    private = list(
        ..attr = NA,
        ..attrscale = NA,
        ..lik = NA,
        ..threshold = NA,
        ..mdropthreshold = NA,
        ..posthoc = NA,
        ..posthocalpha = NA,
        ..attrhoc = NA,
        ..attrhocalpha = NA,
        ..showbarras = NA,
        ..showternary = NA,
        ..showdiagnose = NA)
)

JARScalesResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "JARScalesResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]],
        Consumidores = function() private$.items[["Consumidores"]],
        penalizacion = function() private$.items[["penalizacion"]],
        MeanDropLow = function() private$.items[["MeanDropLow"]],
        MeanDropHigh = function() private$.items[["MeanDropHigh"]],
        barraplot = function() private$.items[["barraplot"]],
        ternaplot = function() private$.items[["ternaplot"]],
        diagplot = function() private$.items[["diagplot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Just-About-Right analysis")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="JAR Descriptives"))
            self$add(jmvcore::Table$new(
                options=options,
                name="Consumidores",
                title="Consumer Research",
                rows="(attr)",
                clearWith=list(
                    "consulow",
                    "consujar",
                    "consuhigh",
                    "flow",
                    "fjar",
                    "fhigh"),
                columns=list(
                    list(
                        `name`="var", 
                        `title`="Attributes", 
                        `type`="text", 
                        `content`="($key)", 
                        `combineBelow`=TRUE),
                    list(
                        `name`="flow", 
                        `title`="freq. Low", 
                        `type`="integer"),
                    list(
                        `name`="fjar", 
                        `title`="freq. Jar", 
                        `type`="integer"),
                    list(
                        `name`="fhigh", 
                        `title`="freq. High", 
                        `type`="integer"),
                    list(
                        `name`="consulow", 
                        `title`="Low (%)", 
                        `type`="number"),
                    list(
                        `name`="consujar", 
                        `title`="Jar (%)", 
                        `type`="number"),
                    list(
                        `name`="consuhigh", 
                        `title`="High (%)", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="penalizacion",
                title="Weighted-penalty analysis",
                rows="(attr)",
                visible="(lik)",
                clearWith=list(
                    "penalty",
                    "penaltyttest",
                    "penaltyse",
                    "penaltyp",
                    "penaltyalpha",
                    "penaltysig"),
                columns=list(
                    list(
                        `name`="var", 
                        `title`="Attributes", 
                        `type`="text", 
                        `content`="($key)", 
                        `combineBelow`=TRUE),
                    list(
                        `name`="penalty", 
                        `title`="Weighted penalty", 
                        `type`="number"),
                    list(
                        `name`="penaltyttest", 
                        `title`="t <sub>value</sub>", 
                        `type`="number", 
                        `visible`="(attrhoc)"),
                    list(
                        `name`="penaltyse", 
                        `title`="Std. error", 
                        `type`="number", 
                        `visible`="(attrhoc)"),
                    list(
                        `name`="penaltyp", 
                        `title`="p <sub>value</sub>", 
                        `type`="number", 
                        `format`="zto,pvalue", 
                        `visible`="(attrhoc)"),
                    list(
                        `name`="penaltyalpha", 
                        `title`="Alpha", 
                        `type`="number", 
                        `format`="zto,pvalue", 
                        `visible`="(attrhoc)"),
                    list(
                        `name`="penaltysig", 
                        `title`="Significant", 
                        `type`="text", 
                        `visible`="(attrhoc)"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="MeanDropLow",
                title="Penalty analysis (Level Low)",
                rows="(attr)",
                visible="(lik)",
                clearWith=list(
                    "droplow",
                    "qlow",
                    "selow",
                    "tukeylow",
                    "alphalow",
                    "siglow"),
                columns=list(
                    list(
                        `name`="var", 
                        `title`="Attributes", 
                        `type`="text", 
                        `content`="($key)", 
                        `combineBelow`=TRUE),
                    list(
                        `name`="droplow", 
                        `title`="Mean-drop low", 
                        `type`="number"),
                    list(
                        `name`="qlow", 
                        `title`="q <sub>value</sub>", 
                        `type`="number", 
                        `visible`="(posthoc)"),
                    list(
                        `name`="selow", 
                        `title`="Std. error", 
                        `type`="number", 
                        `visible`="(posthoc)"),
                    list(
                        `name`="tukeylow", 
                        `title`="p <sub>tukey</sub>", 
                        `type`="number", 
                        `format`="zto,pvalue", 
                        `visible`="(posthoc)"),
                    list(
                        `name`="alphalow", 
                        `title`="Alpha", 
                        `type`="number", 
                        `format`="zto,pvalue", 
                        `visible`="(attrhoc)"),
                    list(
                        `name`="siglow", 
                        `title`="Significant", 
                        `type`="text", 
                        `visible`="(posthoc)"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="MeanDropHigh",
                title="Penalty analysis (Level High)",
                rows="(attr)",
                visible="(lik)",
                clearWith=list(
                    "drophigh",
                    "qhigh",
                    "sehigh",
                    "tukeyhigh",
                    "alphahigh",
                    "sighigh"),
                columns=list(
                    list(
                        `name`="var", 
                        `title`="Attributes", 
                        `type`="text", 
                        `content`="($key)", 
                        `combineBelow`=TRUE),
                    list(
                        `name`="drophigh", 
                        `title`="Mean-drop high", 
                        `type`="number"),
                    list(
                        `name`="qhigh", 
                        `title`="q <sub>value</sub>", 
                        `type`="number", 
                        `visible`="(posthoc)"),
                    list(
                        `name`="sehigh", 
                        `title`="Std. error", 
                        `type`="number", 
                        `visible`="(posthoc)"),
                    list(
                        `name`="tukeyhigh", 
                        `title`="p <sub>tukey</sub>", 
                        `type`="number", 
                        `format`="zto,pvalue", 
                        `visible`="(posthoc)"),
                    list(
                        `name`="alphahigh", 
                        `title`="Alpha", 
                        `type`="number", 
                        `format`="zto,pvalue", 
                        `visible`="(attrhoc)"),
                    list(
                        `name`="sighigh", 
                        `title`="Significant", 
                        `type`="text", 
                        `visible`="(posthoc)"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="barraplot",
                title="Barplot of attributes",
                width=640,
                height=320,
                renderFun=".plot3",
                visible="(showbarras)"))
            self$add(jmvcore::Image$new(
                options=options,
                name="ternaplot",
                title="Ternary Plot of attributes",
                width=640,
                height=640,
                renderFun=".plot",
                visible="(showternary)"))
            self$add(jmvcore::Image$new(
                options=options,
                name="diagplot",
                title="Diagnostic Plot of attributes",
                width=640,
                height=640,
                renderFun=".plot2",
                visible="(showdiagnose)"))}))

JARScalesBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "JARScalesBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "FoodieStats",
                name = "JARScales",
                version = c(1,0,0),
                options = options,
                results = JARScalesResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Just-About-Right Analysis
#'
#' 
#' @param data .
#' @param attr .
#' @param attrscale .
#' @param lik .
#' @param threshold .
#' @param mdropthreshold .
#' @param posthoc .
#' @param posthocalpha .
#' @param attrhoc .
#' @param attrhocalpha .
#' @param showbarras .
#' @param showternary .
#' @param showdiagnose .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$Consumidores} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$penalizacion} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$MeanDropLow} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$MeanDropHigh} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$barraplot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$ternaplot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$diagplot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$Consumidores$asDF}
#'
#' \code{as.data.frame(results$Consumidores)}
#'
#' @export
JARScales <- function(
    data,
    attr,
    attrscale = "Five",
    lik,
    threshold = 20,
    mdropthreshold = 1,
    posthoc = TRUE,
    posthocalpha = 95,
    attrhoc = TRUE,
    attrhocalpha = 95,
    showbarras = FALSE,
    showternary = FALSE,
    showdiagnose = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("JARScales requires jmvcore to be installed (restart may be required)")

    if ( ! missing(attr)) attr <- jmvcore::resolveQuo(jmvcore::enquo(attr))
    if ( ! missing(lik)) lik <- jmvcore::resolveQuo(jmvcore::enquo(lik))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(attr), attr, NULL),
            `if`( ! missing(lik), lik, NULL))

    for (v in attr) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- JARScalesOptions$new(
        attr = attr,
        attrscale = attrscale,
        lik = lik,
        threshold = threshold,
        mdropthreshold = mdropthreshold,
        posthoc = posthoc,
        posthocalpha = posthocalpha,
        attrhoc = attrhoc,
        attrhocalpha = attrhocalpha,
        showbarras = showbarras,
        showternary = showternary,
        showdiagnose = showdiagnose)

    analysis <- JARScalesClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

