
# This file is automatically generated, you probably don't want to edit this

sensorywheelOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "sensorywheelOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            showdescription = FALSE,
            levv = NULL,
            wheelstyle = "faded",
            colorselection = "JamoviStylish",
            nodesize = 6,
            leafsize = 6,
            labelcolors = "Black",
            nodelabelrotation = FALSE,
            leaflength = "Default", ...) {

            super$initialize(
                package="FoodieStats",
                name="sensorywheel",
                requiresData=TRUE,
                ...)

            private$..showdescription <- jmvcore::OptionBool$new(
                "showdescription",
                showdescription,
                default=FALSE)
            private$..levv <- jmvcore::OptionVariables$new(
                "levv",
                levv,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..wheelstyle <- jmvcore::OptionList$new(
                "wheelstyle",
                wheelstyle,
                options=list(
                    "unsorted",
                    "sorted",
                    "faded"),
                default="faded")
            private$..colorselection <- jmvcore::OptionList$new(
                "colorselection",
                colorselection,
                options=list(
                    "JamoviStylish",
                    "BeachStylish",
                    "OceanStylish",
                    "Pastel1",
                    "Heat",
                    "Market",
                    "Terrain",
                    "Gingerbread",
                    "Umami",
                    "SummerSalad",
                    "FruitCup",
                    "Delight",
                    "Greensmoothie",
                    "Turmeric",
                    "Snacks",
                    "Sashimi",
                    "Macarons",
                    "Feast",
                    "Veggies",
                    "Beetroot",
                    "Spice",
                    "Sweet",
                    "Tropical",
                    "Breakfast",
                    "Carrots",
                    "Stick",
                    "Tea",
                    "Decadent",
                    "Berry",
                    "Sugary",
                    "Citrus",
                    "Chard",
                    "Shrimp",
                    "SweetSalad",
                    "Cheesecake",
                    "FruitBasket",
                    "Cayenne",
                    "Smoothie",
                    "Mojito",
                    "Coffee",
                    "Wine",
                    "Beer",
                    "Fish",
                    "Cheese",
                    "Bread",
                    "Chocolate",
                    "Beef",
                    "Honey",
                    "Dairy",
                    "Vegetables",
                    "Bean",
                    "Seafood",
                    "Octopus",
                    "Gummy",
                    "Random"),
                default="JamoviStylish")
            private$..nodesize <- jmvcore::OptionNumber$new(
                "nodesize",
                nodesize,
                default=6,
                min=1,
                max=10)
            private$..leafsize <- jmvcore::OptionNumber$new(
                "leafsize",
                leafsize,
                default=6,
                min=1,
                max=10)
            private$..labelcolors <- jmvcore::OptionList$new(
                "labelcolors",
                labelcolors,
                options=list(
                    "Black",
                    "Darkblue",
                    "Orange",
                    "White"),
                default="Black")
            private$..nodelabelrotation <- jmvcore::OptionBool$new(
                "nodelabelrotation",
                nodelabelrotation,
                default=FALSE)
            private$..leaflength <- jmvcore::OptionList$new(
                "leaflength",
                leaflength,
                options=list(
                    "Default",
                    "Short",
                    "Medium",
                    "Large",
                    "Verylarge"),
                default="Default")

            self$.addOption(private$..showdescription)
            self$.addOption(private$..levv)
            self$.addOption(private$..wheelstyle)
            self$.addOption(private$..colorselection)
            self$.addOption(private$..nodesize)
            self$.addOption(private$..leafsize)
            self$.addOption(private$..labelcolors)
            self$.addOption(private$..nodelabelrotation)
            self$.addOption(private$..leaflength)
        }),
    active = list(
        showdescription = function() private$..showdescription$value,
        levv = function() private$..levv$value,
        wheelstyle = function() private$..wheelstyle$value,
        colorselection = function() private$..colorselection$value,
        nodesize = function() private$..nodesize$value,
        leafsize = function() private$..leafsize$value,
        labelcolors = function() private$..labelcolors$value,
        nodelabelrotation = function() private$..nodelabelrotation$value,
        leaflength = function() private$..leaflength$value),
    private = list(
        ..showdescription = NA,
        ..levv = NA,
        ..wheelstyle = NA,
        ..colorselection = NA,
        ..nodesize = NA,
        ..leafsize = NA,
        ..labelcolors = NA,
        ..nodelabelrotation = NA,
        ..leaflength = NA)
)

sensorywheelResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "sensorywheelResults",
    inherit = jmvcore::Group,
    active = list(
        description = function() private$.items[["description"]],
        wheeloptions = function() private$.items[["wheeloptions"]],
        showheelplot = function() private$.items[["showheelplot"]],
        wheelplot = function() private$.items[["wheelplot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Sensory Wheel Analysis")
            self$add(jmvcore::Html$new(
                options=options,
                name="description",
                title="description",
                visible="(showdescription)"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="wheeloptions"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="showheelplot"))
            self$add(jmvcore::Image$new(
                options=options,
                name="wheelplot",
                title="Sensory Wheel Plot",
                width=960,
                height=960,
                renderFun=".plot",
                requiresData=TRUE))}))

sensorywheelBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "sensorywheelBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "FoodieStats",
                name = "sensorywheel",
                version = c(1,0,0),
                options = options,
                results = sensorywheelResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Sensory Wheel Analysis
#'
#' 
#' @param data .
#' @param showdescription .
#' @param levv .
#' @param wheelstyle .
#' @param colorselection .
#' @param nodesize .
#' @param leafsize .
#' @param labelcolors .
#' @param nodelabelrotation .
#' @param leaflength .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$description} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$wheeloptions} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$showheelplot} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$wheelplot} \tab \tab \tab \tab \tab Flavor Wheel \cr
#' }
#'
#' @export
sensorywheel <- function(
    data,
    showdescription = FALSE,
    levv,
    wheelstyle = "faded",
    colorselection = "JamoviStylish",
    nodesize = 6,
    leafsize = 6,
    labelcolors = "Black",
    nodelabelrotation = FALSE,
    leaflength = "Default") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("sensorywheel requires jmvcore to be installed (restart may be required)")

    if ( ! missing(levv)) levv <- jmvcore::resolveQuo(jmvcore::enquo(levv))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(levv), levv, NULL))

    for (v in levv) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- sensorywheelOptions$new(
        showdescription = showdescription,
        levv = levv,
        wheelstyle = wheelstyle,
        colorselection = colorselection,
        nodesize = nodesize,
        leafsize = leafsize,
        labelcolors = labelcolors,
        nodelabelrotation = nodelabelrotation,
        leaflength = leaflength)

    analysis <- sensorywheelClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

